### ISSUE TITLE
Swarm-Pybullet environment dies after running for a while

### ISSUE THREAD

**Issue by tu-trinh** [VT-Collab/choice-sets#42]
Hi, I'm currently working on a project related to agents learning from demonstration and I was attempting to use your environments for testing. When I run the swarm environment with `python3 main.py` (using instructions from the README), the environment starts up and I am able to move the Cheez-its box and cars around, but it dies after around 10 seconds with this message
```
pybullet build time: Oct 31 2022 19:04:54
Version = 4.1 INTEL-14.7.26
Vendor = Intel Inc.
Renderer = Intel Iris Pro OpenGL Engine
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
```
I'm also unable to click/open/work with any of the sidebar items, and the three plots on the left always show straight lines.

I'd love to be able to play around with the environment and run experiments with it. Please let me know if there's anything I should do to be able to interact with it! Thanks :)

**Comment by ajonnavittula** [comment]
Hey,

When you use `main.py`, it runs only for `4*np.pi` timesteps. If you'd like to run it for longer, you need to change that to a different value. As far as the sidebar items, they are simply camera renders for the system. We have not implemented any camera renders in the environment at the moment. This simulation was made in pyBullet. Therefore, I would recommend looking at their API document for more information on how to edit this. You can find more information [here](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3). Good luck!
